name: 打包测试

on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: 部署
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3 # 检出代码
      with:
        fetch-depth: 0  # 需要完整历史以确保子模块或其它依赖正确检出

    - name: 设置Node.js
      uses: actions/setup-node@v3 # 安装Node.js
      with:
        node-version: '20'  # 更新到Node.js 20.x

    - name: 安装包依赖
      run: npm install # 安装依赖

    - name: 创建打包
      run: npm run build # 打包

    - name: 开始部署
      uses: peaceiris/actions-gh-pages@v3 # 部署
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/